// <auto-generated />
using System;
using AlocacaoDeVeiculos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlocacaoDeVeiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("CAT_ATIVO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CAT_DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CAT_NOME");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CAT_VALOR_DIARIA");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORIA");
                });

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLI_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLI_CPF");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLI_DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLI_EMAIL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLI_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CLI_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CLI_SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLI_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("TB_CLIENTE");
                });

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.LocacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarroPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CAR_PLACA");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_ID");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOC_CRIADO_EM");

                    b.Property<DateTime>("DataPrevDevolucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOC_DATA_PREV_DEVOLUCAO");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOC_DATA_RETIRADA");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("LOC_STATUS");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LOC_VALOR_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("CarroPlaca");

                    b.HasIndex("ClienteId");

                    b.ToTable("TB_LOCACAO");
                });

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.VeiculoModel", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CAR_PLACA");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("CAR_ANO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("CAR_ATIVO");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CAT_ID");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAR_COR");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit")
                        .HasColumnName("CAR_DISPONIVEL");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAR_IMAGEM_URL");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAR_MARCA");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAR_MODELO");

                    b.HasKey("Placa");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TB_CARRO");
                });

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.LocacaoModel", b =>
                {
                    b.HasOne("AlocacaoDeVeiculos.Models.VeiculoModel", "VeiculoObj")
                        .WithMany()
                        .HasForeignKey("CarroPlaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlocacaoDeVeiculos.Models.ClienteModel", "ClienteObj")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteObj");

                    b.Navigation("VeiculoObj");
                });

            modelBuilder.Entity("AlocacaoDeVeiculos.Models.VeiculoModel", b =>
                {
                    b.HasOne("AlocacaoDeVeiculos.Models.CategoriaModel", "CategoriaObj")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaObj");
                });
#pragma warning restore 612, 618
        }
    }
}
